clickbait_prompt: >
  Create a Dataset for clickbait detection task.  
  Label each headline as clickbait or not.  
  Clickbait headlines manipulate attention, exaggerate facts, or promise surprising outcomes.  
  Label is binary: 1 for clickbait, 0 for non-clickbait.  
  Output is JSON Format.

  Example 1:  
  Input text: "You won’t believe what this doctor just revealed about the COVID vaccine!"  
  Output JSON Syntax: {  
    "Clickbait": 1  
  }

  Example 2:  
  Input text: "Health Ministry announces changes to COVID-19 vaccination schedule"  
  Output JSON Syntax: {  
    "Clickbait": 0  
  }

  Example 3:  
  Input text: "This vaccine side effect will SHOCK you – experts stunned!"  
  Output JSON Syntax: {  
    "Clickbait": 1  
  }

  Example 4:  
  Input text: "Official data shows increase in vaccination rates across Europe"  
  Output JSON Syntax: {  
    "Clickbait": 0  
  }

  Example 5:  
  Input text: "Ha detto QUESTO prima di perdere le elezioni – incredibile!"  
  Output JSON Syntax: {  
    "Clickbait": 1  
  }

  Example 6:  
  Input text: "Election results show close race between leading candidates"  
  Output JSON Syntax: {  
    "Clickbait": 0  
  }

  Input text:

annotation_prompts:
  conspiracy_prompt: > 
    Create a dataset for conspiracy theory detection.

    Task:
    Identify and extract expressions in input text that explicitly or implicitly suggest:
    - existence of secret plots 
    - involvement of powerful hidden actors
    - coordinated deception carried out covertly

    The conspiracy must be presented without verifiable evidence, relying on insinuation, distrust of institutions, or speculative language.

    Important Guidelines:
    - ONLY extract exact textual spans from the input. DO NOT paraphrase.
    - DO NOT label:
      - factual statements
      - unverifiable but non-conspiratorial concerns
      - generalized distrust without reference to secret plans or actors
    - Preserve the original language (e.g., Italian, English, etc.)
    - Output must be a valid JSON object with key: "conspiracy"

      Example 1:  
      Input text: "While the official numbers suggest a steady recovery, many believe that the government is hiding the truth about the virus to push their own agenda."  
      Output JSON Syntax: {  
        "conspiracy": ["the government is hiding the truth about the virus to push their own agenda"]  
      }

      Input text: "Alcuni utenti sul forum hanno affermato che Big Pharma non vuole che la gente sappia che la cura è naturale, e che la stanno sopprimendo per proteggere i loro profitti."  
      Output JSON Syntax: {  
        "conspiracy": ["Big Pharma non vuole che la gente sappia che la cura è naturale", "la stanno sopprimendo per proteggere i loro profitti"]  
      }

      Example 3:  
      Input text: "According to the post, the real reason for the lockdowns isn’t public health, but a secret plan to control the population using fear and digital surveillance."  
      Output JSON Syntax: {  
        "conspiracy": ["a secret plan to control the population using fear and digital surveillance"]  
      }

      Example 4:  
      Input text: "The article discusses misinformation on social media, where people claim that elections are always rigged and that votes are manipulated by a deep state."  
      Output JSON Syntax: {  
        "conspiracy": ["elections are always rigged", "votes are manipulated by a deep state"]  
      }

      Example 5:  
      Input text: "The Health Minister presented the latest data on COVID-19 recovery rates, and emphasized the importance of public trust in scientific guidelines."  
      Output JSON Syntax: {  
        "conspiracy": []  
      }

      Input text:

  hate_speech_prompt: >
    Create a dataset for hate and toxic speech detection.

    Task:
    Identify and extract expressions from input text that fall into one of the following categories:
    - "hate_speech": explicit hate or threats towards individuals or groups
    - "racist": language expressing racial or ethnic prejudice
    - "sexist": language expressing gender-based discrimination or misogyny
    - "toxic_speech": insults, demeaning language, or generalized offensive tone

    Guidelines:
    - ONLY extract spans from the input text. DO NOT paraphrase.
    - Do NOT label factual statements, neutral content, or unverifiable opinions.
    - The same phrase should not appear in multiple categories. Assign each phrase to the most specific and relevant key.
    - Preserve the original language of the text (multilingual input is allowed).
    - Output must be a single valid JSON object with keys: "hate_speech", "racist", "sexist", "toxic_speech".
    - If no expressions apply for a given key, assign an empty list: "key": [].
    
    Example 1:
    Input text: "I’m absolutely sick of immigrants coming here and taking our jobs. They don’t appreciate our culture, and now they’re trying to change everything to suit their needs. Go back to your country, we don’t want you here."
    Output JSON Syntax: {
      "hate_speech": ["I’m absolutely sick of immigrants coming here and taking our jobs", "they’re trying to change everything to suit their needs"],
      "racist": ["Go back to your country", "we don’t want you here"],
      "sexist": [],
      "toxic_speech": []
    }

    Example 2:
    Input text: "You’re just another loudmouth feminist who got a job because of a diversity quota. All you do is complain, and no one cares about your whining. Why don’t you just sit down and let the real professionals handle it?"
    Output JSON Syntax: {
      "hate_speech": ["no one cares about your whining", "Why don’t you just sit down and let the real professionals handle it"],
      "racist": [],
      "sexist": ["another loudmouth feminist", "got a job because of a diversity quota"],
      "toxic_speech": ["You’re just another loudmouth feminist"]
    }

    Example 3:
    Input text: "Sei una scusa inutile per una persona. Non sopporto guardarti, sta' zitto una volta per tutte. Non aggiungi nulla a questa conversazione e probabilmente non lo farai mai."
    Output JSON Syntax:{
      "hate_speech": [],
      "racist": [],
      "sexist": [],
      "toxic_speech": ["Sei una scusa inutile per una persona", "sta' zitto una volta per tutte", "Non aggiungi nulla a questa conversazione"]
    }

    Example 4:
    Input text: "I understand why people question the effectiveness of some historical policies, but saying that the Holocaust was exaggerated or that the moon landing was faked is not only ignorant, it’s disrespectful. We must respect the facts, even when they don’t fit our narrative."
    Output JSON Syntax:{
      "hate_speech": [],
      "racist": [],
      "sexist": [],
      "toxic_speech": ["saying that the Holocaust was exaggerated", "the moon landing was faked"]
    }

    Example 5:
    Input text: "The discussion about climate change has been polarizing, but it is important to engage in respectful conversations based on science. Everyone should be open to learning more and not dismiss ideas just because they don’t align with our personal beliefs."
    Output JSON Syntax: {
      "hate_speech": [],
      "racist": [],
      "sexist": [],
      "toxic_speech": []
    }

    Input text:

  trolling_prompt: >
    Create a Dataset for trolling detection task.

    Task: Label spans of the input text that provoke, mock or manipulate others to create emotional reactions or conflict.

    Important Instructions:
    - ONLY extract spans from the input text. DO NOT paraphrase.
    - Label only provocative or manipulative statements. Ignore factual information or neutral content.
    - Return the result as a JSON object under the key "trolling".
    - Group similar phrases together in the array. Do not repeat identical values.

    Example 1:
    Input text: "È davvero incredibile come tu possa pensare di avere sempre ragione. Ogni volta che parli sembra che nessuno ti stia ascoltando, eppure continui a insistere con le tue idee senza senso!"
    Output JSON Syntax: {
    "trolling": ["È davvero incredibile come tu possa pensare di avere sempre ragione", "sembra che nessuno ti stia ascoltando", "continui a insistere con le tue idee senza senso"]
    }

    Example 2:
    Input text: "Haha, you're still talking about that? What a joke!"
    Output JSON Syntax: {
    "trolling": ["you're still talking about that?", "What a joke!"]
    }

    Example 3 :
    Input text: "Honestly, it's laughable how you think anyone cares about your opinion. You're just a bystander, trying to sound like an expert when you have no idea what you're talking about."
    Output JSON Syntax: {
    "trolling": ["it's laughable how you think anyone cares about your opinion", "trying to sound like an expert when you have no idea what you're talking about"]
    }

    Example 4:
    Input text: "You really think that idea is going to work? Honestly, I wouldn't get my hopes up if I were you, but I guess you're just too stubborn to listen."
    Output JSON Syntax: {
    "trolling": ["You really think that idea is going to work?", "I wouldn't get my hopes up if I were you", "you're just too stubborn to listen"]
    }

    Example 5:
    Input text: "The team has been working hard to improve the project, and we're making good progress. We'll need to gather more data to ensure we’re heading in the right direction."
    Output JSON Syntax: {
    "trolling": []
    }

    Input text: 

  discredit_prompt: >
    Create a dataset for discrediting language detection.

    Identify and extract only those expressions that explicitly or implicitly:
    - attack political parties, institutions, individuals, experts, or public figures.
    - with the intent or effect of undermining their credibility, trust, or legitimacy.

    These expressions may include:
    - insults, delegitimizing claims, pejorative labels
    - assertions of incompetence, dishonesty, manipulation
    - ridicule, sarcasm used to discredit

    Important Guidelines:
    - Label only phrases from the input text, using exact span match.
    - Do not paraphrase.
    - DO NOT label:
      - factual critiques with evidence
      - neutral or polite disagreement
      - unverifiable claims not targeting credibility
    - Group all extracted values under the single key: "discredit"
    - Avoid redundancy (no repeated values)
    - Preserve the original language of the input text. 
    - Output must be a valid JSON object with the key: "discredit"

    Example 1:
    Input text: "Molto spesso non c'è da fidarsi di quello che dicono i politici. Ogni giorno si recano al lavoro, ma sono solo burattini nelle mani dei grandi interessi economici. Rilasciano interviste giornalmente, ed ogni cosa che dicono è manipolata per i loro scopi. È incredibile come le loro parole possano influenzare il pubblico senza che nessuno si ponga domande."
    Output JSON Syntax: {
    "discredit": ["Non c'è da fidarsi di quello che dicono i politici", "sono solo burattini nelle mani dei grandi interessi economici", "Ogni cosa che dicono è manipolata per i loro scopi"]
    }

    Example 2:
    Input text: "That so-called expert is just parroting information they've heard. They don't even try to do their own research. It's surprising how many people still believe what they're saying. But the truth is, they have no real understanding of the subject. It’s all just surface-level knowledge that anyone can look up. How can anyone trust such shallow knowledge when it’s obvious they don’t grasp the complexity of the issue?"
    Output JSON Syntax: {
    "discredit": ["That so-called expert is just parroting information they've heard", "they have no real understanding of the subject", "How can anyone trust such shallow knowledge when it’s obvious they don’t grasp the complexity of the issue?"]
    }

    Example 3:
    Input text: "Don't trust any vaccine recommendations. People often act like they know better, but they’re just parroting what they’ve heard. The pharmaceutical companies are just out to make money, and they don’t care about your health. It's shocking how they manipulate people's fears to sell their products. They are more interested in controlling the population. If you look closely, you'll see how they profit from your fear, manipulating the situation for their benefit."
    Output JSON Syntax: {
    "discredit": ["Don't trust any vaccine recommendations", "The pharmaceutical companies are just out to make money", "They are more interested in controlling the population"]
    }

    Example 4:
    Input text: "While some say the mainstream media is reliable, anyone who truly looks into the matter knows that the truth is always hidden from the public."
    Output JSON Syntax: {
    "discredit": ["anyone who truly looks into the matter knows that the truth is always hidden from the public"]
    }

    Example 5:
    Input text: "The government has recently announced several new public health initiatives aimed at improving the well-being of citizens. These include better access to healthcare and increased funding for medical research."
    Output JSON Syntax: {
    "discredit": []
    }

    Input text: 

  pseudoscience_prompt: >
    Create a dataset for pseudoscience detection.

    Identify and extract verbatim expressions that:
    - Promote scientifically false, disproven, or unverified claims
    - Present these claims as if they were established scientific facts
    - Lack credible peer-reviewed support, falsifiability, or empirical reproducibility

    Typical categories include:
    - Alternative medicine presented as cure
    - Anti-vaccine misinformation
    - Claims involving energy fields, chakras, quantum healing
    - Flat Earth, chemtrails, anti-gravity, etc.
    - Misuse of scientific terminology to create false authority

    Important Guidelines:
    - Label only exact phrases from the input text.
    - Do NOT infer or paraphrase.
    - Do not label:
      - Expressions of doubt or questions
      - Speculation clearly marked as such
      - Religious or spiritual beliefs unless explicitly framed as science

    - All extracted values must be placed under the key: "pseudoscience"
    - Preserve the original language of the input text (do not translate)
    - Output must be a valid JSON object.

    Example 1:
    Input text:
    "Many people believe that maintaining a positive mindset can physically eliminate tumors, although there's no medical evidence. At the same time, regular medical checkups are essential for early detection of serious conditions."
    Output JSON Syntax: {
      "pseudoscience": ["maintaining a positive mindset can physically eliminate tumors"]
    }

    Example 2:
    Input text:
    "While the scientific community urges caution, some holistic practitioners suggest that placing crystals on the body can realign your energy fields. Additionally, detox foot pads are marketed as a way to draw toxins out of your body overnight. Meanwhile, drinking plenty of water is recommended by doctors."
    Output JSON Syntax: {
      "pseudoscience": ["placing crystals on the body can realign your energy fields", "detox foot pads are marketed as a way to draw toxins out of your body overnight"]
    }

    Example 3:
    Input text:
    "Sunlight helps with vitamin D synthesis, but some blogs falsely claim that you can cure depression entirely just by walking barefoot on the earth. There are also statements circulating that suggest essential oils can treat ADHD in children, despite lack of robust trials."
    Output JSON Syntax: {
      "pseudoscience": ["you can cure depression entirely just by walking barefoot on the earth", "essential oils can treat ADHD in children"]
    }

    Example 4:
    Input text:
    "Una dieta equilibrata è fondamentale per la salute. Tuttavia, alcuni siti alternativi affermano che bere acqua strutturata aumenta la frequenza vibrazionale del corpo, favorendo la rigenerazione cellulare. È importante distinguere tra raccomandazioni nutrizionali basate su prove e concetti privi di validazione scientifica."
    Output JSON Syntax: {
      "pseudoscience": ["bere acqua strutturata aumenta la frequenza vibrazionale del corpo, favorendo la rigenerazione cellulare"]
    }

    Example 5:
    Input text:
    "According to recent guidelines, washing your hands reduces transmission of infectious diseases. Clinical trials have demonstrated that vaccines are safe and effective in preventing illness."
    Output JSON Syntax:{
      "pseudoscience": []
    }

    Input text: 

  #polarity_prompt: